project:
  type: website

website:
  title: "Buddhayana"
  reader-mode: true
  sidebar:
    logo: logo.png
    title: "<b>Buddhayana:</b> musings of a modern household practitioner"
    style: floating
    search: true
    collapse-level: 1
    background: white
    contents:
      - xinxinming.qmd
      - earth-touching.qmd
      - sutras.qmd
      - indonesia.qmd
      - section: Four Dharmas of Gampopa
        href: gampopa/index.qmd
        contents:
          - gampopa/mind-one-with-dharma.qmd
          - gampopa/dharma-progress-along-path.qmd
          - gampopa/path-clarify-confusion.qmd
          - gampopa/confusion-dawn-as-wisdom.qmd
      - section: Yang-style tai chi
        href: tai-chi/index.qmd
        contents:
          - tai-chi/daoist-exercises.qmd

format:
  html:  
    toc: true
    toc-location: right
    grid:
      sidebar-width: 350px
      margin-width: 350px
    link-external-newwindow: true
reference-location: margin
citation-location: margin
filters:
  - nutshell




