project:
  type: website

website:
  title: "Following Gampopa"
  sidebar:
    logo: /images/green-buddhist-bodhi-leaf-removebg-preview.png
    style: docked  
    search: true
    collapse-level: 1
    background: light
    contents:
      - section: Four Dharmas of Gampopa
        href: four-dharmas-gampopa/index.qmd
        contents:
          - four-dharmas-gampopa/mind-one-with-dharma.qmd
          - four-dharmas-gampopa/dharma-progress-along-path.qmd
          - four-dharmas-gampopa/path-clarify-confusion.qmd
          - four-dharmas-gampopa/confusion-dawn-as-wisdom.qmd
      - sutras.qmd
      - about.qmd
format:
  html:  
    toc: true
    toc-location: right
    grid:
      sidebar-width: 350px
      margin-width: 350px
    theme:
      - sandstone
      - gampopa.scss
    css: styles.css
    link-external-newwindow: true
reference-location: margin
citation-location: margin
filters:
  - nutshell




